Account Management Views & Controllers/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;
using ASPSnippets.GoogleAPI;
using System.Web.Script.Serialization;

using Tyme.Models;
using Tyme.Controllers;
using System.Runtime.InteropServices;
using System.Net.Http;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.WebSockets;
using System.Drawing;
using System.Text;

namespace TimeManager.Controllers
{
    public class ClientController : Controller
    {
        private TymeDataEntities db = new TymeDataEntities();
        // GET: Client
        public ActionResult Index()
        {
            return View();
        }

        // GET: Login
        public ActionResult Login()
        {
            if (Session["ResetView"] != null)
            {
                Response.Write("<script>alert('" + Session["ResetView"].ToString() + "')</script>");
                Session.Remove("ResetView");
                Session.Remove("validReset");
            }
            if (Session["ForgotPassword"] != null)
            {
                Response.Write("<script>alert('" + Session["ForgotPassword"].ToString() + "')</script>");
                Session.Remove("ForgotPassword");
            }

            if (Request.QueryString["error"] == "access_denied")
            {
                Response.Write("<script>alert('Error! Could not authorize a Google Account.')</script>");
                return RedirectToAction("Login");
            }
            else if (!string.IsNullOrEmpty(Request.QueryString["code"]))
            {
                string code = Request.QueryString["code"];
                string json = GoogleConnect.Fetch("me", code);
                GoogleProfile profile = new JavaScriptSerializer().Deserialize<GoogleProfile>(json);
                //scan the database for the email given
                foreach (User check in db.Users)
                {
                    if (check.email == profile.Email.ToString())
                    {
                        //found same email in our database, sign them in
                        Session["user"] = check;
                        if (check.image != null) setMySrcFromUser(check);
                        return RedirectToAction("Index");
                    }
                }
                //end of loop, didn't find a corresponding user
                //register our new user without a password
                //only can sign in with google
                //regular login will send you an email in order to register
                User newUser = new User();
                //only need an email but we'll try to make registration easier
                if (profile.Name.ToString() != null)
                {
                    newUser.name = profile.Name.ToString();
                }
                else
                {
                    newUser.name = "Google";
                }
                newUser.email = profile.Email.ToString();
                newUser.password = null;
                newUser.salt = null;
                newUser.image = null;
                newUser.isAdmin = "n";
                db.Users.Add(newUser);
                db.SaveChanges();
                foreach (User check in db.Users)
                {
                    if (check.email == newUser.email)
                    {
                        //found same email in our database, sign them in
                        Session["user"] = check;
                        if (check.image != null) setMySrcFromUser(check);
                        break;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["googleClientId"] = "52904577299-5nh8vsemuuu6evd8v0c2bh0ivdr7po1p.apps.googleusercontent.com";

            return View();
        }

        // POST: Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string email, string password, string Login, string Google)
        {
            if (Login != null)
            {
                foreach (User check in db.Users)
                {
                    PasswordStorage ps = new PasswordStorage();
                    if (check.email == email)
                    {
                        if (ps.VerifyPassword(check.salt + password, check.password))
                        {
                            Session["user"] = check;
                            if (check.image != null) setMySrcFromUser(check);

                            return RedirectToAction("Index");
                        }
                    }
                }
            }
            if(Google != null)
            {
                return RedirectToAction("Google");
            }
            return RedirectToAction("Login");
        }

        public ActionResult Google()
        {
            GoogleConnect.ClientId = "52904577299-5nh8vsemuuu6evd8v0c2bh0ivdr7po1p.apps.googleusercontent.com";
            GoogleConnect.ClientSecret = "AAantZfmV8k0YpAdI6KAFSEr";
            GoogleConnect.RedirectUri = "https://localhost:44311/Client/Login";
            GoogleConnect.Authorize("profile", "email");
            
            return RedirectToAction("Login");
        }
        // GET: Register
        public ActionResult Register()
        {
            return View();
        }

        // POST: Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "Id,name,email,password,isAdmin,image")] User user, HttpPostedFileBase fileToUpload)
        {
            if (ModelState.IsValid)
            {
                user.isAdmin = "n";
                if (fileToUpload != null)
                {
                    user = this.addMyImageToUser(user, fileToUpload); //Inserts image and returns user
                }
                string theSalt = CreateSalt();
                user.salt = theSalt;
                PasswordStorage ps = new PasswordStorage();
                user.password = ps.CreateHash(theSalt + user.password);
                db.Users.Add(user);
                db.SaveChanges();
                
                foreach (User check in db.Users)
                {
                    if (check.email.ToString() == user.email)
                    {
                        Session["user"] = check;
                        if (check.image != null) setMySrcFromUser(check);

                        return RedirectToAction("ShowAccount");
                    }
                }
                
            }
            return View();
        }

        public string CreateSalt()
        {
            Random r = new Random();
            // Decide how long the salt will be
            int strLength = r.Next(1, 10);

            var sb = new StringBuilder();

            for (int i = 0; i < strLength; i++)
            {
                // Decide whether to add an uppercase letter, a lowercase letter, or a number
                int whichType = r.Next(0, 3);
                switch (whichType)
                {
                    // Lower case letter
                    case 0:
                        sb.Append((char)(97 + r.Next(0, 26)));
                        break;
                    // Upper case letter
                    case 1:
                        sb.Append((char)(65 + r.Next(0, 26)));
                        break;
                    // Number
                    case 2:
                        sb.Append((char)(48 + r.Next(0, 10)));
                        break;
                }
            }

            return sb.ToString();
        }

        // GET: ShowAccount
        public ActionResult ShowAccount()
        {
            if (Session["user"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User currentUser = (User)Session["user"];
            User user = db.Users.Find(currentUser.Id);
            if (user == null)
            {
                return HttpNotFound();
            }
            if(user.password != null)
            {
                ViewData["isPasswordHasValue"] = "YES";
            }
            return View(user);
        }

        // POST: ShowAccount(Save Changes to Account)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShowAccount([Bind(Include = "Id,name,email,password,isAdmin,image")] User user, HttpPostedFileBase fileToUpload)
        {
            if (ModelState.IsValid)
            {
                if (fileToUpload != null)
                {
                    user = this.addMyImageToUser(user, fileToUpload); //Inserts image and returns user
                    this.setMySrcFromUser(user);
                }
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("ShowAccount");
        }

        // POST: SaveChanges
        public ActionResult Logout()
        {
            Session.Remove("user");
            Session.Remove("userPPImage");
            return RedirectToAction("Login");
        }

        // GET: ForgotPassword
        public ActionResult ForgotPassword()
        {
            if(Session["ForgotPassword"] != null)
            {
                Response.Write("<script>alert('"+ Session["ForgotPassword"].ToString() +"')</script>");
                Session.Remove("ForgotPassword");
            }

            return View();
        }

        // POST: ForgotPassword
        [HttpPost]
        [ValidateAntiForgeryToken]

Account Management Views & Controllers/Views/Client/Dashboard.cshtml

@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/Clients_Layout.cshtml";
}

<div style="text-align:left;">
    <label style="float:left; font-weight:normal; font-size:30px; padding-right:30px;">Dashboard</label>
    <div style="float:left; padding-top:10px">
        <label style="font-weight:normal; font-size:15px;">sort:</label>
        <select class="dropdown" name="sort" id="sort" style="font-weight:normal; font-size:15px;">
            <option value="alphabetical">alphabetical</option>
            <option value="daily first">daily first</option>
            <option value="monthly">monthly</option>
            <option value="new custom">new custom</option>
        </select>
    </div>
    <div style="float:none; text-align:right; padding-top:10px;">
        <btn class="btn btn-sm" style="font-weight:normal;">
            <svg class="bi bi-search" width="1.5em" height="1.5em" viewBox="0 0 15 15" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z" />
                <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z" />
            </svg>
        </btn>
        <input type="search" id="search" name="search" placeholder="search" style="font-weight:normal; font-size:15px;" />
    </div>
    <hr />
</div>
<div style="text-align:left; margin-left:0px; padding-top:3em; margin-bottom:3em;">
    @for (int card = 1; card <= 3; card++)
    {
        <div class="img-rounded" style="width:45%; float:left; background-color:InfoBackground; border-radius:1.5em; border:0.1em solid lightgray; margin-bottom:3em;">
            <div style="margin-top:1em; margin-left:10%; font-size:1em; color:black;">
                <p style="text-align:left; font-weight:bold; font-size:1.5em; float:left;">Bike Deliveries</p>
                <a style="float:right; padding-right:2.5em; margin-top:1em;" href="~/Views/Client/ViewCard.cshtml">
                    <svg class="bi bi-info-square" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="darkblue" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                        <path d="M8.93 6.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588z" />
                        <circle cx="8" cy="4.5" r="1" />
                    </svg>
                </a>
                <p style="text-align:left; font-weight:normal; clear:both;">June 1 - June 28</p>
            </div>
            <div style="overflow-y:scroll; max-height:15em; margin-right:1em; background-color:white;">
                @for (double contentRow = 1; contentRow <= 28; contentRow++)
                {
                    <p style="margin:0 0; padding-right:1.5%; width:10%; text-align:right; color:black; float:left; font-weight:bold; clear:left; background-color:InfoBackground;">@contentRow</p>
                    <p style="margin: 0 0; width: 90%; background-color: darkblue; float: left; border: 0.05em solid lightgray;">&nbsp;</p>
                }
            </div>
            <p style="margin: 0 0; height: 10%; clear: both;">&nbsp;</p>
        </div>
        if (card % 2 != 0)
        {
            <p style="margin: 0 0; width: 10%; float: left;">&nbsp;</p>
        }
    }
</div>
<br />
<div style="text-align:left; margin-left:0px; padding-top:3em; margin-bottom:3em;">
        <div class="img-rounded" style="width:100%; float:left; background-color:InfoBackground; border-radius:1.5em; border:0.1em solid lightgray; margin-bottom:3em;">
            <div style="margin-top:1em; margin-left:5%; margin-right:5%; font-size:1em; color:black;">
                <p style="text-align:left; font-weight:bold; font-size:2em; float:left;">Calendar</p>
                <a style="float:left;" href="~/Views/Client/ViewCard.cshtml"><img style="width:2em; height:2em; margin-left:0.5em; margin-top:0.5em;" src="~/Content/infoBtn.png" /></a>
                <p style="text-align:left; font-weight:normal; clear:both;">June 2020</p>
            </div>
            <div style="margin-left:5%; margin-right:5%;">
                @for (double dayOfMonth = 1; dayOfMonth <= 28; dayOfMonth++)
                {
                    <div style="width:13%; margin-right:0.5em; margin-bottom:0.5em; float:left;">
                         <p style="margin-bottom:0px; text-align:left; padding-left:0.5em; border-top-right-radius:0.5em; border-top-left-radius:0.5em; background-color:lightgray; color:white; font-weight:bold; clear:both;">@dayOfMonth</p>
                         <div style="background-color:white; border-bottom-left-radius:0.5em; height:5em; border-bottom-right-radius:0.5em; border:0.2em solid lightgray;">
                             <p style="text-align:left; height:1em; width:100%; margin-bottom:0px; font-weight:normal; clear:both; background-color:darkred;">&nbsp;</p>
                             <p style="text-align:left; height:1em; width:100%; margin-top:0px; font-weight:normal; clear:both; background-color:darkblue;">&nbsp;</p>
                         </div>
                    </div>
                }
            </div>
            <p style="margin: 0 0; height: 10%; clear: both;">&nbsp;</p>
        </div>
</div>
<br />

Account Management Views & Controllers/Views/Client/ForgotPassword.cshtml
@model Tyme.Models.User
@{
    ViewBag.Title = "ForgotPassword";
    Layout = "~/Views/Shared/Clients_Layout.cshtml";
}

<h2>Password Email</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <hr />
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", required = true } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Send Email" class="btn btn-success"><br /> <br />
                @Html.ActionLink("Login", "Login")
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Account Management Views & Controllers/Views/Client/Google.cshtml

@{
    ViewBag.Title = "Google";
    Layout = "~/Views/Shared/Clients_Layout.cshtml";
}

<h2>Google Authentication Page</h2>

<p>Error. Sorry, we couldn't connect your google account.</p>

Account Management Views & Controllers/Views/Client/Index.cshtml

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Clients_Layout.cshtml";
}


Account Management Views & Controllers/Views/Client/Inspiration.cshtml

@{
    ViewBag.Title = "Inspiration";
    Layout = "~/Views/Shared/Clients_Layout.cshtml";
}

<h2>Inspiration</h2>


Account Management Views & Controllers/Views/Client/Login.cshtml
@model Tyme.Models.User
<script src="https://apis.google.com/js/platform.js" async defer>
</script>
<meta name="google-signin-client_id" content=@ViewData["googleClientId"]>

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/Clients_Layout.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <h2>Login &nbsp;<button type="submit" name="Google" id="Google" style="border: 0.5px solid black;" class="btn"><img src="~/Content/GoogleIcon.png" style="margin-right:5px;" width="25" height="25" /> Sign in with Google</button></h2>
    </div>
} 

<table class="table">
    <tr>
        <td>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <br />
                <div class="form-horizontal">
                    <div class="form-group">
                        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", required = true } })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control", type = "password", required = true } })
                            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">

                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Login" name="Login" id="Login" class="btn btn-primary" /> &nbsp;
                            @Html.ActionLink("Forgot Password", "ForgotPassword") |
                            @Html.ActionLink("Register", "Register")
                        </div>
                    </div>
                </div>
            }
        </td>
    </tr>
</table>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Account Management Views & Controllers/Views/Client/Register.cshtml
@model Tyme.Models.User

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/Clients_Layout.cshtml";
}

<h2>Register</h2>

@using (Html.BeginForm("Register", "Client", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", required = true } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", required = true } })
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control", type = "password", required = true } })
            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class = "control-label col-md-2" >profile image</label>
        <div class="col-md-10">
            <input type="file" id="fileToUpload" name="fileToUpload">
            @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Register" class="btn btn-success" /> <br /><br />
            @Html.ActionLink("Login", "Login")
        </div>
    </div>
</div>
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Account Management Views & Controllers/Views/Client/ResetView.cshtml
@model Tyme.Models.User
@{
    ViewBag.Title = "ResetMe";
    Layout = "~/Views/Shared/Clients_Layout.cshtml";
}

<h2>Set Password</h2>
@if (Session["validReset"] != null)
{
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <hr />
            <div class="form-group">
                @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2", placeholder="your new password" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control", required = true } })
                    @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                </div>
            </div>
            <br /><br /><br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Reset Password" class="btn btn-success"><br /> <br />
                    @Html.ActionLink("Register", "Register") |
                    @Html.ActionLink("Login", "Login")
                </div>
            </div>
            <br /><br /><br />
        </div>
    }
}
else
{
    <p>Sorry, seems to be an invalid link.</p>
    <br />
    <br />
    @Html.ActionLink("Register", "Register")
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Account Management Views & Controllers/Views/Client/ShowAccount.cshtml
@model Tyme.Models.User
@{
    ViewBag.Title = "ShowAccount";
    Layout = "~/Views/Shared/Clients_Layout.cshtml";
}

<h2>Your Account</h2>

@using (Html.BeginForm("ShowAccount", "Client", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.isAdmin)

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", required = true } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", type = "email", required = true } })
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="padding-top:0.5em;">
            @if (ViewData["isPasswordHasValue"] == null)
            {
                <p>This account was started with Google. Set a password here to Login with Us.</p>
                @Html.ActionLink("set password", "ForgotPassword")
            }
            else
            {
                <a href="~/Views/Client/ForgotPassword.cshtml">new password</a>
            }

        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">profile image</label>
        <div class="col-md-10" style="padding-top:0.5em;">
            <input type="file" id="fileToUpload" name="fileToUpload">
            @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save Changes" class="btn btn-success">&nbsp;&nbsp;
            @Html.ActionLink("Logout", "Logout")
        </div>
    </div>
</div>
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Account Management Views & Controllers/Views/Client/ViewCard.cshtml

@{
    ViewBag.Title = "ViewCard";
    Layout = "~/Views/Shared/Clients_Layout.cshtml";
}

<h2>ViewCard</h2>
